### ISSUE TITLE
[I] Empty navigation panel when QON is opened minimized

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#2110]
#### Expected behaviour
The navigation pane should load the note structure from the first start

#### Actual behaviour
The structure is only loaded after switching between other notes

#### Steps to reproduce
1. Enable the option to load the last opened note when starting QON
2. Enable the option to start minimized.
3. Close the program and open it again

[video](https://upload.vaa.red/2jPr4#UfXFgXvjVkfpRRfAtyhv57EV2Pvb7TbU)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

```
**Version**: `21.4.1`
**Build date**: `Apr 17 2021`
**Build number**: `827`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
```
</details>

edit: update the steps to reproduce

**Comment by pbek** [comment]
>    Enable the option to load the last opened note when starting QON
>    Close the program and open it again

I did that and the navigation panel shows the structure from the last note.

**Comment by pbek** [comment]
Do you also have this issue when you open a fresh session of QON, by using the `--session` parameter?

**Comment by fabianski7** [comment]
hmm... quite strange, with a fresh section I don't have this problem

**Comment by pbek** [comment]
I can't see it in the video, but do you have the navigation panel in tabs? Maybe it has something to do with that?

**Comment by fabianski7** [comment]
> I can't see it in the video, but do you have the navigation panel in tabs? Maybe it has something to do with that?

yes, it is together with another panel. but it doesn't seem to be the problem, because I separated it and the bug continued

**Comment by fabianski7** [comment]
Well, I think I have now managed to reproduce it in a fresh profile. You need to enable the option to start minimized.

**Comment by pbek** [comment]
> You need to enable the option to start minimized.

Strange, I don't use that setting anywhere.

**Comment by fabianski7** [comment]
https://i.imgur.com/6LuJI8I.png

**Comment by pbek** [comment]
Is the content of the navigation panel rendered when you edit the note after the application starts?

**Comment by fabianski7** [comment]
> Is the content of the navigation panel rendered when you edit the note after the application starts?

Yes. when I type anything in the editor, the navigation panel is rendered

**Comment by pbek** [comment]
The content of the navigation panel is re-generated every time the highlighter of the edit panel does something and the navigation panel is visible. For some reason that's not the case on your system when you start QON.

**Comment by fabianski7** [comment]
It is not a problem in my system.
Look at these tests I did on two virtual machines, with two different distros (kde neon and fedora) and on two different DE (plasma and gnome).

before, of course, I followed the steps I described

> 1. Enable the option to load the last opened note when starting QON
> 2. Enable the option to start minimized.
> 3. Close the program and open it again

<details><summary>KDE Neon</summary>

https://user-images.githubusercontent.com/47755037/115993823-0c17ee00-a5c4-11eb-8c43-1653e8e49076.mp4

</details>

<details><summary>Fedora</summary>


For some reason QON keeps loading for a long time before displaying the window, but still the bug is reproducible


https://user-images.githubusercontent.com/47755037/115998025-df200700-a5d4-11eb-8ff7-2c6d86b5bb54.mp4



</details>

In both the problem is the same as I reported.

**Comment by pbek** [comment]
I though starting it minimized was the workaround to make it work, sorry.

**Comment by pbek** [comment]
Nevertheless I wasn't able to reproduce your issue on my KDE Neon machine yet.

**Comment by fabianski7** [comment]
I don't know how else it can be reproduced.
With the virtual machines, I only enabled the options that are in the [screenshot](https://i.imgur.com/6LuJI8I.png) I sent earlier, because the option to load the last opened file when starting QON is already enabled by default.

**Comment by pbek** [comment]
I'll attempt to fix it blindly...

**Comment by pbek** [comment]
## 21.4.6
- a possible problem with generating the header tree in the navigation panel when
  starting the application minimized was fixed

**Comment by fabianski7** [comment]
it didn't work, at least not on my system.
As soon as possible I will try again on the VMs.

**Comment by pbek** [comment]
If the QON windows was opened via the try icon the the header tree in the navigation panel will be generated again if the panel is visible.

**Comment by fabianski7** [comment]
> If the QON windows was opened via the try icon the the header tree in the navigation panel will be generated again if the panel is visible.

Indeed, through the icon in the systray the bug does not happen. 
I believe that the commit 
9590bdf is what fixed this, as I tested a version before it and starting QON from the systray didn't display the navigation panel correctly either. kudos!

However the bug still happens if started via the desktop shortcut. I tested the 21.5.2 version of QON in kde neon.

**Comment by fabianski7** [comment]
> > However the bug still happens if started via the desktop shortcut.
> 
> Which shortcut? The global shortcut?

ops, sorry. the desktop icon

**Comment by fabianski7** [comment]
> > the desktop icon
> 
> that uses above mentioned commit... I don't know what happens differently on your KDE system than on mine. sweat_smile

there is nothing different.
if it were a problem with my setup, it would not be possible to reproduce in other installations, as was possible in kde neon and fedora 34
