### ISSUE TITLE
[I] Bold and italic text in header is small

### ISSUE THREAD

**Issue by FireFragment** [pbek/QOwnNotes#2369]
#### Expected behaviour

Bold and italic text inside header should be of the same size as the header itself.

#### Actual behaviour

Bold and italic text inside header is smaller, than the header itself, like in the screenshot:
![35](https://user-images.githubusercontent.com/55660550/148427097-19efae33-79cf-4b93-91c4-f94eaaed3151.png)

#### Steps to reproduce

1. Choose a theme with bigger headers, than the rest of the text.
 2. Create a new note
 3. Paste the following snippet:
    ```markdown
    # Header with **bold text** and *italic text*
    ```

-----

I think the problem is, that in `Settings → Interface → Editor → Editor fonts & colors`, the `Adapt font size` percentage is calculated from `Text preset` font size, not from parent (in this case header) font size.

**Comment by pbek** [comment]
Your opinion, @Waqar144?

**Comment by Waqar144** [comment]
We need to merge with the current block level format. The linked PR should fix it hopefully

**Comment by pbek** [comment]
@Waqar144, careful with the word "fixes" in PRs... GitHub closes the issue issue if such a PR is accepted... 😅

**Comment by pbek** [comment]
## 22.1.5
- italic and bold formatted text in headlines will now have the same size as the headline
  (for [#2369](https://github.com/pbek/QOwnNotes/pull/2369), thank you @Waqar144)

**Comment by Waqar144** [comment]
Ah, didn't know it worked across repos too

**Comment by pbek** [comment]
Yes, seems so that "works" too (and it still can't be turned off 😅)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by FireFragment** [comment]
It works now, thank you!

**Comment by pbek** [comment]
Thank you for testing!
