### ISSUE TITLE
Characters and words count

### ISSUE THREAD

**Issue by fred-g** [pbek/QOwnNotes#536]
Hi,

I mostly use your app for writing long texts.
Can you please add a way to see characters (space included) and words count ?

It will be very good if it is in real time in the status bar. Else, a popup menu to see the document statistic will do it ;)

Best regards.

++

**Comment by pbek** [comment]
You could write a custom script that outputs the information to the log panel...
See: <http://docs.qownnotes.org/en/develop/scripting/README.html#registering-a-custom-action>

**Comment by fred-g** [comment]
Yes, I saw that but I am not familiar wit Qt.
I will try.

Thanks anyway.

**Comment by pbek** [comment]
Scripts are written in JavaScript.
@Maboroshy is the master of all things scripted. :wink:

You need to get the current note (see: <http://docs.qownnotes.org/en/develop/scripting/README.html#getting-the-current-note>) and get the `noteText` from it. Then you could count the characters and words of it.

**Comment by Maboroshy** [comment]
Your summon looks like a challenge. 
I would try using qtquick pop-up window for result instead of log output instead of log panel.

By the way, is it possible to have qtquick driven scriptable panel? That's a counter-challenge :wink:

I don't need it personally, but it seems perfect for the task.

**Comment by Maboroshy** [comment]
Here is the prototype: 
```qml
import QtQml 2.0
import com.qownnotes.noteapi 1.0
import QtQuick 2.3
import QtQuick.Dialogs 1.2
    
MessageDialog {
    title: "Note statistics"
    
    function init() {
        script.registerCustomAction("statNote", "Show note statistics", "Stat");
    }
    
    function statNote(note) {
        return  "Characters: " + note.noteText.match(/[^ ]/gi).length + "\n" + 
                "Words: " + note.noteText.match(/[\w\d]+/gi).length + "\n" + 
                "Lines: " + note.noteText.split(/\r\n|\r|\n/).length
    }
    
    function customActionInvoked(action) {
        if (action == "statNote") {
            text = statNote(script.currentNote())
            visible = true
        }
    }
} 
```

**Comment by pbek** [comment]
@Maboroshy, great job! Did you manage to open a qtquick dialog?

**Comment by Maboroshy** [comment]
I did. The script above fully works, just needs some polish.

**Comment by pbek** [comment]
It really works, you are a genius! Maybe you also want to set a nice freedesktop theme icon for the action and set the last parameter to true to show it in the context menu (if that makes sense).

I'm waiting for a pull request. ;)

Maybe you even want to document how to create dialogs in <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.rst>. :+1:

**Comment by Maboroshy** [comment]
I'll do the pull request, but documenting is too much for me now. The whole object-oriented programming and specifically qtquick is very new for me.

**Comment by Maboroshy** [comment]
But I got characters without spaces while @fred-g wanted them in. Making up obstacles for myself as usual. :smile:

**Comment by pbek** [comment]
> The whole object-oriented programming and specifically qtquick is very new for me.

Just a new paragraph on how to open a dialog, like you did in the script would be more than awesome. :tada:

**Comment by Maboroshy** [comment]
It's not that easy. The dialog is generated when script is initialized. So to make it show some fresh data, like an always changing current note, you need to change it's properties, like text, before showing it. It works little differently for different types of dialogs. There are some more nuances that took me quite a lot of time to work out. So that's much more than a new paragraph. And for any real programmer, who worked with qtquick, it will look like a babytalk of guy who doesn't know what he's writing about.

**Comment by pbek** [comment]
You are the "most real" programmer I'm currently aware of who works with QOwnNotes. :grin: 

>  So to make it show some fresh data, like an always changing current note

Yes, for me the dialog shows the same numbers, when I modify the note and click the "Stats" button again.

**Comment by Maboroshy** [comment]
That will need some more work...

**Comment by Maboroshy** [comment]
I wonder, when is `note.noteText` updated by the app? Because, as far as I understand, the script counts data in `note.noteText` each time custom action invoked. It reacts to the change of current note, so it gets an actual `note.noteText`.
 
Looks like changing note won't change `note.noteText`, even saving changes won't. Reloading note will, and the script will show correct stats.

**Comment by pbek** [comment]
@Maboroshy, you are right! Will be fixed in version 17.03.1! Thank you for finding out.

**Comment by Maboroshy** [comment]
It's actually was you who found that out in previous post. :smile:

**Comment by Maboroshy** [comment]
I'll make a pull request after 17.03.1 release. Mostly final script:
```qml 
import QtQml 2.0
import com.qownnotes.noteapi 1.0
import QtQuick 2.3
import QtQuick.Dialogs 1.2

/* This script will add a custom action with a toolbar button that will show 
 * a current note statistics in a pop-up window. */

MessageDialog {
    
    function init() {
        script.registerCustomAction("statNote", "Show note statistics", "Stats", "view-statistics.svg")
    }
    
    function customActionInvoked(action) {
        if (action == "statNote") {
            
            var note = script.currentNote()
            
            title = "Note statistics"
            text = "Characters (inc. spaces): " + note.noteText.length + "\n" +
                   "Characters (w/o spaces): " + note.noteText.match(/[^ ]/gi).length + "\n" + 
                   "Words: " + note.noteText.split(/\s+/).length + "\n" + 
                   "Paragraphs: " + (note.noteText.match(/^.*?\S/gm) || "").length
            visible = true
        }
    }
} 
```
Issue closed.

**Comment by Maboroshy** [comment]
But a scriptable panel would be much cooler. :wink:

**Comment by pbek** [comment]
If you find a way in QML to create a QDockWidget or to write to one I certainly will integrate one!

**Comment by fred-g** [comment]
Wow, that is so interesting to read you, thank you !

@Maboroshy Yes, in Writing, characters count is spaces included ;)

**Comment by pbek** [comment]
## 17.03.1
- the current note in the scripting function `script.currentNote()` will now 
  be update correctly when when text is written to it by the user

**Comment by Maboroshy** [comment]
Ok then, here we go. I've made some research and found out that you can't just put QML content into QDockWidget. There's a bug in Qt bugtracker, but nobody cares. But...
I think it can be implemented as a special panel that will show a text data generated inside QML script. Mostly like a log panel, but with just last message visible.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
> I think it can be implemented as a special panel that will show a text data generated inside QML script. Mostly like a log panel, but with just last message visible.

We need a way to create a QDockWidget or something... but I don't even know how to store / restore the positions of user generated panels...

**Comment by pbek** [comment]
@Maboroshy or can you also create a new dialog with user interface elements from a QML?

**Comment by Maboroshy** [comment]
It won't be user generated. 
You'll make a new log panel that will show last message sent by QML function. No history, no scrolling, one message. 
I'll make QML that will use something like `script.panel("my text")` to make the output to that panel like we do with the log. I'll put note statics as `"my text"` and invoke this command on `onNoteStored` hook.

As far as I know UI can be fully made on QML but it has less features that C++ Qt, like no QDockWidget and many more.

**Comment by Maboroshy** [comment]
The thing is, to make it right we will need a panel for each script that wants a panel. So it can be like with custom action buttons, with the init thing. Don't know if it's possible for a full scale panels.

**Comment by Maboroshy** [comment]
Tested new build. All good, new stats on each type. I'll go for a pull request.

**Comment by pbek** [comment]
Custom log panels don't sound very intriguing..

**Comment by pbek** [comment]
@Maboroshy your script works great. @fred-g does it work for you?
<https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-stats.qml>

**Comment by Maboroshy** [comment]
>Custom log panels don't sound very intriguing..
Not something you'd put to the CV for sure. :wink: But it will do the job for this and maybe some more issues. 

I've tried making my script to update stats on fly, so it's window could be used like an overlay panel. But looks like QML needs to redraw window to update it properties, and that means a new window at the centre of the screen each update. Not very useful. 

So unless there'll be some C++ UI element, that will show data from QML, it won't be more ergonomic than now.

**Comment by fred-g** [comment]
Awesome !
It works as expected, thank you very much.

Best regards.

**Comment by pbek** [comment]
Thank you for testing.

**Comment by pbek** [comment]
@Maboroshy it would be great if it would be possible to really add UI-elements from a QML...

**Comment by Letterus** [comment]
When I load that script I get these errors:
* module "QtQuick" is not installed
* module "QtQuick.Dialogs" is not installed

What do I have to do to make those modules available?

**Comment by pbek** [comment]
@Letterus you are using macOS, aren't you? @Maboroshy did you ever get such a message? I never had that... (even under macOS)

**Comment by Letterus** [comment]
Yep.. so it should work.. interesting. :-)

**Comment by pbek** [comment]
Although I'm not sure if QtQuick is included in the app bundle on macOS since QOwnNotes doesn't use it by itself... :/ You could either build QOwNotes yourself or output `text` from the script with `script.log()`...

**Comment by pbek** [comment]
## 17.05.1
- there now is a new scripting command to show an information message box
  `script.informationMessageBox()`
    - for more information please take a look at the
      [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#showing-an-information-message-box)

@Maboroshy, you should be able to use it so you can drop QtQuick in your script for @Letterus

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Letterus** [comment]
Yeah, great! Works with the latest dev release!
This is the updated script:

```javascript
import QtQml 2.0;
import com.qownnotes.noteapi 1.0;

/* This script will add a custom action with a toolbar button that will show 
 * a current note statistics in a pop-up window. */

QtObject {
    function init() {
        script.registerCustomAction("statNote", "Show note statistics", "Stats", "view-statistics.svg");
    }
    
    function customActionInvoked(action) {
        if (action == "statNote") {
            
            var note = script.currentNote();
            
            var title = "Note statistics";
            var text = "Characters (inc. spaces): " + note.noteText.length + "\n" +
                   "Characters (w/o spaces): " + note.noteText.match(/[^ ]/gi).length + "\n" + 
                   "Words: " + note.noteText.split(/\s+/).length + "\n" + 
                   "Paragraphs: " + (note.noteText.match(/^.*?\S/gm) || "").length;
            
            script.informationMessageBox(text, title);
        }
    }
}
```

**Comment by Maboroshy** [comment]
Personally I don't like leaving QtQuick for a hard-coded function. Not having QtQuick leaves scripts with no UI but a custom action buttons. I do understand that it's the most appropriate solution though. I didn't know QtQuick wasn't in the app bundle.

I'd prefer for @Letterus to make a pull-request for the script, since he got it working already.

**Comment by pbek** [comment]
> pull-request for the script

fine with me

> And I still think it'd be much better to have script-driven text output to some in-app widget, or at least a status bar

I'm not sure how that should work when multiple scripts are writing to it...

**Comment by Maboroshy** [comment]
Theoretically, like the custom actions:
1) First init function to initialize UI element with some name;
2) Function to send message to UI element by it's name.

**Comment by pbek** [comment]
That UI element do you suggest beside something in the status bar?

**Comment by Maboroshy** [comment]
For now I think only about "text field" dock-widget, that will display, say, note stats, like the ones issue is about. I'd also use it for my external scripts status.

You can tune some script settings with custom actions and see a feedback in the text field.

Text is a powerful thing. It can display statuses, results of script-driven operations or even processes.

**Comment by pbek** [comment]
I'll see what I can do.

**Comment by Letterus** [comment]
Hm, until now I have no experience with Qt/Qml: But how would I access UI elements without QtQuick? f.e. if I want to show a "enter file name" dialog or "select a file to import" dialog for #573 - is there a way?

**Comment by pbek** [comment]
I will add a `QT       += quick` to the project in the next release and see what will happen...

**Comment by pbek** [comment]
@Letterus, if the projects builds you should get a new development release for mac os at <https://github.com/pbek/QOwnNotes/releases> within the next hour. Please tell me how it works for you.

**Comment by pbek** [comment]
And for later: this is the dialog you are searching <http://doc.qt.io/qt-5/qml-qtquick-dialogs-filedialog.htm>

**Comment by pbek** [comment]
@Letterus, this should be the dev release: <https://github.com/pbek/QOwnNotes/releases/download/dev-macosx-b2902-100516/QOwnNotesDev-47074aae26fdc6a79ce314e29f26e5d57966a616.dmg>

**Comment by Letterus** [comment]
I installed build build 2902, but the original script is giving the same error messages even though QtQuick is bundled now:

```
Applications joey$ otool -L QOwnNotes.app/Contents/MacOS/QOwnNotes 
QOwnNotes.app/Contents/MacOS/QOwnNotes:
	@executable_path/../Frameworks/QtSvg.framework/Versions/5/QtSvg (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtGui.framework/Versions/5/QtGui (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtCore.framework/Versions/5/QtCore (compatibility version 5.8.0, current version 5.8.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@executable_path/../Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtQuick.framework/Versions/5/QtQuick (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtQml.framework/Versions/5/QtQml (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtSql.framework/Versions/5/QtSql (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtXmlPatterns.framework/Versions/5/QtXmlPatterns (compatibility version 5.8.0, current version 5.8.0)
	@executable_path/../Frameworks/QtXml.framework/Versions/5/QtXml (compatibility version 5.8.0, current version 5.8.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

I don't understand that. Do you?

**Comment by pbek** [comment]
I'm not sure... @Letterus, what happens if you don't include `QtQuick.Dialogs` in the script?

**Comment by Letterus** [comment]
Error remains, but only for QtQuick…

**Comment by pbek** [comment]
Does Google know something about the error?

**Comment by Letterus** [comment]
[Here](http://stackoverflow.com/questions/42522830/qt-quick-qml-assemble-mac-bundle-not-a-dynamic-library-error-when-using-ma) and [here](https://bugreports.qt.io/browse/QTBUG-57265) is reported there is a severe bug in qtmacdeploy regarding qml. The solution described there is to leave out the parameter `-always-overwrite`.

**Comment by pbek** [comment]
I'm not using such a parameter, here's what I do: <https://github.com/pbek/QOwnNotes/blob/develop/travis/create-dmg.sh>

**Comment by Letterus** [comment]
There are additional hints:
1. Start macdeployqt from its directory. That would be `.macdeployqt $dir/$APP.app` instead of `$QTDIR/bin/macdeployqt ./$APP.app`.
2. Add the directory of the qml files for dependend linking: `macdeployqt <full_path_to_app_bundle>.app -qmldir=<full_path_to_qml_files_folder>`

See: https://forum.qt.io/topic/59030/solved-macdeployqt-problem/9

I don't really know if that really helps though…

**Comment by pbek** [comment]
I don't know, we aren't deploying any qml files... :/

**Comment by Letterus** [comment]
It seems you need to specify qmldir to make QtQuick work:

- https://forum.qt.io/topic/48338/solved-deployment-problem-of-qt-quick-application-on-mac-os-x-10-10-1-qt-5-3-2/3
- http://stackoverflow.com/questions/20895398/cant-deploy-qt-quick-app-to-mac-osx

**Comment by pbek** [comment]
Problem is there is no qml dir because the users can have there qml where they want. :/

**Comment by Letterus** [comment]
Could you just specify a directory with scripts to let the frameworks needed there be linked? Don't know if that will do it, just an idea…

**Comment by pbek** [comment]
I can't link one directory, it wouldn't be the same for every user. Scripts can be stored everywhere... I wonder if it works if you build QOwnNotes yourself or at least install the Qt libraries...

**Comment by pbek** [comment]
That's very strange...

**Comment by Letterus** [comment]
Hm? I can try to build it myself, but I will not find any time this week. So it will be later, maybe next week.

**Comment by pbek** [comment]
@Letterus, for you:

## 17.05.2
- there now is a new scripting command to show an open file dialog `script.getOpenFileName()`
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#showing-an-open-file-dialog)

**Comment by pbek** [comment]
@Maboroshy, for you:

## 17.05.2
- there now are new scripting commands to register labels with
  `script.registerLabel("my-label")` and write to it with
  `script.setLabelText("my-label", "my custom text")`
    - the labels will be visible in the new scripting dock widget
    - for more information please take a look at
      [Registering a label](http://docs.qownnotes.org/en/develop/scripting/README.html#registering-a-label)
      and [Set the text of a registered label](http://docs.qownnotes.org/en/develop/scripting/README.html#set-the-text-of-a-registered-label)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Cool stuff! Compiling now. I'll try to remake the subject script with the new goodies.

**Comment by Maboroshy** [comment]
That was easy. Here's the working script for note stats in one line.
It would look better if minimum height of widget was 3x less. Is it possible?

```qml
import QtQml 2.0
import com.qownnotes.noteapi 1.0

QtObject {
    
    function init() {
        script.registerLabel("note stats")
    }
    
    function noteOpenedHook(note) {
        script.setLabelText("note stats", "Characters (inc. spaces): " + note.noteText.length  +
                   "   Characters (w/o spaces): " + note.noteText.match(/[^ ]/gi).length +
                   "   Words: " + note.noteText.split(/\s+/).length + 
                   "   Paragraphs: " + (note.noteText.match(/^.*?\S/gm) || "").length)
    }
    
    function handleNoteTextFileNameHook(note) {
    script.setLabelText("note stats", "Characters (inc. spaces): " + note.noteText.length  +
                   "   Characters (w/o spaces): " + note.noteText.match(/[^ ]/gi).length +
                   "   Words: " + note.noteText.split(/\s+/).length + 
                   "   Paragraphs: " + (note.noteText.match(/^.*?\S/gm) || "").length)
    }
} 
```

**Comment by pbek** [comment]
@Maboroshy, great stuff!
You could create a function with your setLabelText command and call that to make your script smaller. ;)

**Comment by Maboroshy** [comment]
I'll make some tweaks before pull request. That was to try new goodies.

**Comment by pbek** [comment]
great!

> It would look better if minimum height of widget was 3x less. Is it possible?

I can try to reduce some margins...

**Comment by Letterus** [comment]
Great! I will test the changes as soon as I find some time.

**Comment by Maboroshy** [comment]
I've made a pull request with the new "label" script.

**Comment by pbek** [comment]
@Maboroshy, saw and merged it, thanks a lot!
btw. do you still have troubles with height? the margins are already pretty low... unfortunately the overall initial heights of such widgets are managed by the layout manager and there is almost no chance to alter that...

**Comment by Maboroshy** [comment]
I do. I have minimum widget height equals to 3 text lines. The script needs only one, so there's a lot of wasted space. But it's cosmetic issue. It's much better than pop-up window anyway.

**Comment by pbek** [comment]
Oh, now I know what you mean.
And I finally found a (tricky) way around that!

## 17.05.3
- removed a gray area under the note edit widget (glitch from version 17.05.2)
- you can now reduced the height of the scripting widget and the log widget 
  down to 10 pixel
- you can now reduced the height of the note tag widget until the buttons are
  reached

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
All good. The "label" looks very neat now. I knew you'd find the way to do it. :+1:
I always think, how the app would look like without that grey borders between panes, or with some panes filled with grey to move them out of focus... Will it be more modern and minimalistic or a set back. 
I hope I get more time to play with it. Need to install Qt Creator again...

**Comment by pbek** [comment]
@Maboroshy in the next release the user will be able to install scripts directly from the new script repository https://github.com/qownnotes/scripts where I gave you write access. ;) Feel free to add your great scripts to the repository. I will write some kind of tutorial... It's just a folder with the script and an `info.json` per script.

**Comment by pbek** [comment]
Later it will also be possible to define variable the user can set in the scripting settings for example to set paths to executables that are needed. And there will be a setting to set the platforms the script runs on.

**Comment by pbek** [comment]
@Maboroshy 

## 17.05.5
- you can now access the new [script repository](https://github.com/qownnotes/scripts) from a new button *Search script repository* in the *scripting settings*
    - in the new *script repository* dialog you can search for scripts from 
      the repository and install them
    - more features and scripts will be added in the coming releases

**Comment by pbek** [comment]
@Maboroshy, I added your note stats script to the script repository.

**Comment by Maboroshy** [comment]
Great stuff! I was just thinking about something like it but you already have it done. And it's very easy to pull in script and install them. 

I think "search script repository" menu should become the main one, leaving old manual file-based menu as an advanced section mostly for devs.
 
Maybe author should be shown in info about scripts, so you wouldn't have to explain that it's not your fault that some script ate all notes. Also there should be a list of hooks used by each scripts, so user would know what to expect from it. Maybe it should be a mandatory part of script description.

**Comment by Maboroshy** [comment]
By the way I've rewrote my "nsx2md" script with python, so it's cross-platform now, at least I hope so since I'm yet to test in in Windows. I'll pull it in to it's github repo in a few days. Maybe it can be the first big one with executables and stuff.

**Comment by pbek** [comment]
@Maboroshy, I already implemented the author-thing in the current release and this script will give you a sneak peak of what will come next: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/variables.qml>

> I think "search script repository" menu should become the main one, leaving old manual file-based menu as an advanced section mostly for devs.

It's in a button menu now. Maybe we should do something in the main menu of the app too...

**Comment by pbek** [comment]
> By the way I've rewrote my "nsx2md" script with python

I plan to make it possible to have other files in the script repository too, for example such scripts...

**Comment by Maboroshy** [comment]
The variables thing is useful. I always though I will have to use QtQuick dialog for some complex script settings. This is better. Make sure you add a "file" type that will be set by an appropriate dialog.

**Comment by pbek** [comment]
@Maboroshy 

## 17.05.7
- tried to fix a design glitch with the `Add script` button menu in the 
  script settings on non-highdpi displays
- you can now **register settings variables** in **script**
    - this allows you to let the user configure your script in the script 
      settings
    - currently there are settings types for `string`, `text`, `integer` and 
      `file`
    - take a look at the example at
      [variables.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/variables.qml)
      to understand how this all will work
    - a lot of new useful scripts were added to the script repository, which 
      now can be configured with the script settings variables  
- scripts in the script repository can now use the `minAppVersion` property 
  to state what the minimum version of QOwnNotes has to be for the script to run
    - for an example please take a look at
      [info.json](https://github.com/qownnotes/scripts/blob/master/example-script/info.json)
- there now are two new menu entries in the main menu to open the script 
  settings and to search for scripts in the script repository


There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Not in AUR yet. I'll give it a test once I'll compile the new version.
I'm also waiting for an ability to add extra files to scripts. I will be able to use python scripts as a back-end for direct note file access and some complex stuff. Like nsx2md. Scripts can have predefined relative paths to dependency files, so user won't need to care about it.

**Comment by pbek** [comment]
I installed it from the AUR more than two hours ago...

Am 19.05.2017 21:08 schrieb "Maboroshy" <notifications@github.com>:

**Comment by Maboroshy** [comment]
Maybe my machine got too much uptime. Found it after reboot. Compiling now.

**Comment by pbek** [comment]
Or maybe you had too much uptime, I certainly had... 😸

**Comment by pbek** [comment]
@Maboroshy, I think I'm working too much lately. :)

## 17.05.8
- instead of importing `com.qownnotes.noteapi` and `com.qownnotes.tagapi` in 
  your scripts you now only need to import `QOwnNotesTypes`
- there now are new scripting functions `fromNativeDirSeparators`,
  `toNativeDirSeparators` and `dirSeparator` to work with native file paths
    - for more information please take a look at the
      [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html)
- you can now use the property list `resources` in your `info.json` in the
  *script repository* to specify further files that are present in your script's
  directory and that should be downloaded to be used by your script
    - you can use this for example for other scripts you want to run or for 
      icons in custom actions
    - for example code please take a look at
      [selected-markdown-to-bbcode](https://github.com/qownnotes/scripts/tree/master/selected-markdown-to-bbcode)
- if you register a `property string scriptDirPath;` in your script the 
  property will be filled with the path to the directory where your script is 
  located
    - you can use this for example to access other files that are located in 
      your script's directory

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
You do! Hope. I'll try pulling in nsx2md with these new goodies.

**Comment by pbek** [comment]
I'm looking forward to it! :) I don't even want to remember how many hours I worked this week to get that whole scripting thing going... (and how many times I rewrote certain parts of it this week) :)

**Comment by pbek** [comment]
## 17.05.9
- added information about enabled scripts to the *Debug settings*
- now information about the currently installed version of the script will be 
  shown in the *Script repository* if the script is already installed
- you can now also reinstall or update your scripts in the *Script repository*
- the user interface of the *Scripting settings* was adapted to make the 
  entering of script settings more clear
- fixed a problem with automatically setting the name of a local script in 
  the *Scripting settings*

There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
New version works for me. Script settings look nicer now.

Maybe the path to script should stay with the script name. It's going down when settings appear. 

Also maybe selecting directories should be enabled for QFileDialog, or maybe there should be "directory" setting type.

But I'm still not close to using it. I'm on a rampage to make nsx2md to import note tags directly to db.

**Comment by Maboroshy** [comment]
Script settings tend to blend and multiply when going from one script to another.
I've imported "md to bbcode" script which has a "pandoc" setting. Selected it first time - one setting, which is ok. Selected second time - two pandoc settings, which is not ok, etc.

**Comment by pbek** [comment]
@Maboroshy, damn, I didn't took care about removing those widgets before setting them again and I didn't even notice it while testing... Thank you for mentioning!

**Comment by pbek** [comment]
## 17.05.10
- fixed duplication of script settings variables in the in the *Scripting settings*
- moved the qml path settings above the script variable settings in the
  *Scripting settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Duplication issue is resolved, and script path don't jump up and down anymore, which is a good thing.

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
@Maboroshy we need more scripts from you in the repository! :smiley: Your note stats script is so far the number one installed script! :clap: :tada:

**Comment by Maboroshy** [comment]
I'd say I'm working on it, but that is not true. Truth is I'm trying hard to find some time to work on it. But I will prevail!

**Comment by pbek** [comment]
You will prevail, my friend!

**Comment by Maboroshy** [comment]
For some reason "integer" type setting can't be higher than 99.

**Comment by pbek** [comment]
might be a stupid default setting, I will take a look at it

**Comment by Maboroshy** [comment]
I also get weird bug when shown settings may become out of sync with real settings. It's very hard to find out why it happens. May be I miss something obvious. 

I wanted to make the note stats script customizable. Here's the test version:
```qml 
import QtQml 2.0
import QOwnNotesTypes 1.0

Script {
    
    property string charSpaceName
    property string charSpaceLeftName
    property string charSpaceLeftTarget
    property string charNoSpaceName
    property string charNoSpaceLeftName
    property string charNoSpaceLeftTarget
    property string wordsName
    property string wordsLeftName
    property string wordsLeftTarget
    property string paragraphsName
    property string paragraphsLeftName
    property string paragraphsLeftTarget
    
    property variant settingsVariables: [
        {
            "identifier": "charSpaceName",
            "name": "Characters including spaces counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "Chars",
        },
        {
            "identifier": "charSpaceLeftName",
            "name": "Characters including spaces left until target counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "Chars left",
        },
        {
            "identifier": "charSpaceLeftTarget",
            "name": "Target number of characters including spaces",
            "description": "Put number of characters including spaces to count down to",
            "type": "integer",
            "default": "0",
        },
        {
            "identifier": "charNoSpaceName",
            "name": "Characters without spaces counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "",
        },
        {
            "identifier": "charNoSpaceLeftName",
            "name": "Characters without spaces left until target counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "",
        },
        {
            "identifier": "charNoSpaceLeftTarget",
            "name": "Target number of characters without spaces",
            "description": "Put number of characters without spaces to count down to",
            "type": "integer",
            "default": "0",
        },
        {
            "identifier": "wordsName",
            "name": "Words counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "Words",
        },
        {
            "identifier": "wordsLeftName",
            "name": "Words left until target counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "Words left",
        },
        {
            "identifier": "wordsLeftTarget",
            "name": "Target number of words",
            "description": "Put number of words to count down to",
            "type": "integer",
            "default": "0",
        },
        {
            "identifier": "paragraphsName",
            "name": "Paragraphs counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "",
        },
        {
            "identifier": "paragraphsLeftName",
            "name": "Paragraphs left until target counter name",
            "description": "Put a counter name here or leave empty to disable",
            "type": "string",
            "default": "",
        },
        {
            "identifier": "paragraphsLeftTarget",
            "name": "Target number of paragraphs",
            "description": "Put number of paragraphs to count down to",
            "type": "integer",
            "default": "0",
        }
    ]
    
    function init() {script.registerLabel("note stats")}
    
    function noteStats(note) {
        
        var entry = "<td align=center>%1 <b>%2</b></th>\n"
        var entryLeft = "<td align=center>%1 <b>%2 / %3</b></th>\n"
        
        if (charSpaceName !== "") {
            var charSpace = entry.arg(charSpaceName)
                                 .arg(note.noteText.length)
        }
        else {var charSpace = ""}
        
        if (charSpaceLeftName !== "") {
            var charSpaceLeft = entryLeft.arg(charSpaceLeftName)
                                         .arg(charSpaceLeftTarget - note.noteText.length)
                                         .arg(charSpaceLeftTarget)
        }
        else {var charSpaceLeft = ""}
        
        if (charNoSpaceName !== "") {
            var charNoSpace = entry.arg(charNoSpaceName)
                                   .arg(note.noteText.match(/[^ ]/gi).length)
        }
        else {var charNoSpace = ""}
        
        if (charNoSpaceLeftName !== "") {
            var charNoSpaceLeft = entryLeft.arg(charNoSpaceLeftName)
                                           .arg(charNoSpaceLeftTarget - note.noteText.match(/[^ ]/gi).length)
                                           .arg(charNoSpaceLeftTarget)
        }
        else {var charNoSpaceLeft = ""}
        
        if (wordsName !== "") {
            var words = entry.arg(wordsName).arg(note.noteText.split(/\s+/).length)
        }
        else {var words = ""}
        
        if (wordsLeftName !== "") {
            var wordsLeft = entryLeft.arg(wordsLeftName)
                                     .arg(wordsLeftTarget - note.noteText.split(/\s+/).length)
                                     .arg(wordsLeftTarget)
        }
        else {var wordsLeft = ""}
        
        if (paragraphsName !== "") {
            var paragraphs = entry.arg(paragraphsName)
                                  .arg((note.noteText.match(/^.*?\S/gm) || "").length)
        }
        else {var paragraphs = ""}   
        
        if (paragraphsLeftName !== "") {
            var paragraphsLeft = entryLeft.arg(paragraphsLeftName)
                                          .arg(paragraphsLeftTarget - (note.noteText.match(/^.*?\S/gm) || "").length)
                                          .arg(paragraphsLeftTarget)
        }
        else {var paragraphsLeft = ""} 
        
        script.setLabelText("note stats", "<table align=center width=90%>\n<tr>\n" + 
        charSpace + charSpaceLeft + charNoSpace + charNoSpaceLeft + words + wordsLeft + paragraphs + paragraphsLeft + 
        "</tr>\n</table>")
    }
    
    function noteOpenedHook(note) {noteStats(note)}
    function onNoteStored(note) {noteStats(note)}
} 
```
When I change the first integer setting - the "Target number of characters including spaces", the "number of characters" indicator is gone, while being on in settings. And they are not any way connected in the script. Changing settings on and on I get more such weird bugs.

**Comment by pbek** [comment]
Do you overwrite one of the settings properties in your script?
And you seemed to have defined all settings properties as string, but configured some of them as integer in `settingsVariables`. Does that cause any troubles?

**Comment by Maboroshy** [comment]
I don't overwrite anything, only make some "if" checks.
Having integer setting as QML strings doesn't cause any trouble. If I remember correctly, you change them to integer in C++ anyway. I've corrected it, but the issue is not resolved. Maybe that weird connection between settings vars, which is not in the script, changed after that.
Where are the in-script settings stored?

**Comment by pbek** [comment]
In-script settings are stored in the app-wide sqlite database (along with the script entries).

## 17.05.11
- the full integer range of values can now be selected in the number selector
  in script variables in the *Scripting settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
@Maboroshy does the integer field work for you?

**Comment by Maboroshy** [comment]
They do, thanks. I'm yet to instigate what's wrong with my script settings.

**Comment by pbek** [comment]
Thank you for testing!

**Comment by pbek** [comment]
@Maboroshy, I'm working on your dream of custom script dock widgets that can make full use of QtQuick, so that a script can has it's own QtQuick dock widget with it's own user interface! Quite tricky to implement...

**Comment by Maboroshy** [comment]
Have you decided to bundle QtQuick with the app?

**Comment by pbek** [comment]
That would be a consequence.

Am 10.06.2017 12:29 schrieb "Maboroshy" <notifications@github.com>:

**Comment by pbek** [comment]
@Maboroshy, do you have any thoughts about QtQuick?

**Comment by Maboroshy** [comment]
About using it?

It was quite obvious before you've implemented script settings, "labels" and some dialogues. Because back then user could send something to a script only by custom action buttons and mostly could get nothing out. It's not that obvious now.

For example lets take an "attachments pane" script.  For now we can easily implement a label that will show all the note's attachments, maybe even links to open them straight away from the pane. That's a core functionality in place.
Now we bring QtQuick in. The pane becomes not a rusty text string but a UI where every attachment is a button, each have a delete button that will delete link and file after a confirmation. But that's a 3 times more work to implement.

QtQuick will really shine in a very complex scripts, like a reminder or a task manager. But I don't think we will see many of those in repository soon. The amount of work for them is close to making a stand-alone app.

**Comment by pbek** [comment]
> The amount of work for them is close to making a stand-alone app.

yes and no. yes, it still but be work but a new app would definitely be a multitude more work (with all its foundation that needs to be laid out) :)

**Comment by pbek** [comment]
## 26.6.4

- Added an optional editor setting to show character, word and line counts in the
  status bar (for [#536](https://github.com/pbek/QOwnNotes/issues/536))
